### ISSUE TITLE
Minecraft crash when step "ret"

### ISSUE THREAD

**Issue by nrot** [ToroCraft/Minecoprocessors#10]
> java.lang.ArrayIndexOutOfBoundsException: -1
> 	at net.torocraft.minecoprocessors.processor.Processor.processRet(Processor.java:533)
> 	at net.torocraft.minecoprocessors.processor.Processor.process(Processor.java:372)
> 	at net.torocraft.minecoprocessors.processor.Processor.tick(Processor.java:301)
> 	at net.torocraft.minecoprocessors.blocks.TileEntityMinecoprocessor.func_73660_a(TileEntityMinecoprocessor.java:129)
> 	at net.minecraft.world.World.func_72939_s(World.java:1802)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
> 	at java.lang.Thread.run(Thread.java:748)

Try write simple loop:

>  mov ports, 1000b
> mov b, 0
> mov a, 20
> mul 20
> loop:
>     cmp pr, 1
>     jz loop
>     cmp a, b
>     jnz pulse
>     jz to
>     jmp loop
> pulse:
>     mov b, 0
>     mov pl, 15
>     ret
> to: 
>     mov pl, 0
>     inc b
>     ret

[crash-2017-08-25_23.49.57-server.txt](https://github.com/ToroCraft/Minecoprocessors/files/1252998/crash-2017-08-25_23.49.57-server.txt)

**Comment by frodare** [comment]
Thanks for reporting this.  You need execute a `call` before `ret`, however that should only crash the redstone processor and not the entire game.

**Comment by nrot** [comment]
Thanks for answer. Good luck u
