### ISSUE TITLE
In-game guide

### ISSUE THREAD

**Issue by josephcsible** [ToroCraft/Minecoprocessors#12]
Can you add an in-game assembler guide, possibly just a copy of what's on the wiki now?

**Comment by frodare** [comment]
Interesting idea.  What are you thinking, like make a book that you can get from the processor with the processor details? Are you looking for information on the processor and commands, or more of a how-to with example programs?

**Comment by josephcsible** [comment]
More like a reference, so basically the contents of the [Processor Details](https://github.com/ToroCraft/Minecoprocessors/wiki/Processor-Details) page.

**Comment by frodare** [comment]
I want to attempt to solve this issue using hover popups, like the ones when you hover over an item.  If that doesn't work out, my next idea would be to put a book icon (button) on the GUI that opens the details when clicked on.

**Comment by josephcsible** [comment]
I don't think that things like the list of opcodes will work well as hover popups, so I think the book icon/button is the way to go. (Although there are a few things that the hover popups would work well for, so we may as well do both.)

**Comment by frodare** [comment]
Yeah, that's a good point.
