### ISSUE TITLE
Signed book does not run

### ISSUE THREAD

**Issue by Gribbleshnibit8** [ToroCraft/Minecoprocessors#2]
Once a book is signed, placing it back into the Minecoprocessor results in the "Next" statement line containing all the text of the book, and it does not process.
![2017-06-16_23 29 29](https://user-images.githubusercontent.com/5009427/27250124-a5b931fc-52eb-11e7-93a2-7a10223a6a15.png)

**Comment by frodare** [comment]
Thanks for reporting this, I guess I never tested the final build with a signed book ;)

**Comment by frodare** [comment]
This should be fixed in v1.1
