### ISSUE TITLE
 Suggestion on the wiki

### ISSUE THREAD

**Issue by vlad1vv1** [ToroCraft/Minecoprocessors#3]
Hi, your mod really liked. I would ask for a more detailed description of which bit corresponds to which side, that would not be confusing  In the format 0001b.

" Also, the only way to read read redstone values from a port register is to set the port as an input port as we did in the first line of the program."   After that it is necessary to explain which port corresponds to which side, please.

Ask, are there 40 ticks or seconds?

mov c, 40
loop:
dec c
jnz loop

**Comment by frodare** [comment]
Thanks for the suggestion, I do need to spend more time working on the wiki.  

The port mappings are here: https://github.com/ToroCraft/Minecoprocessors/wiki/Processor-Details#port-register-bit-mapping.  So `0001b` would set front port to an input and the rest to outputs.  The front port has a slightly brighter red stripe, and is pointing away from the player when placed.

The processor currently runs at the redstone tick rate of 10Hz.  Therefore, that loop should take just over 8 seconds to run.

**Comment by vlad1vv1** [comment]
Hi, there are a few more moments. If there are several blocks, for example "and" and "or" and others and put them side by side and have the same texture, then in this case you can forget what's where. 
Also it is necessary to pull out the book with a feather and to look that there it is written. 
This is not very convenient. But I did not find a solution to this problem. Change the texture depending on the code, it's very difficult. 
Have a question! To edit a book with a pen, you have to erase all the code. Can you make a not-vanilla book with a normal editor?

**Comment by frodare** [comment]
@vlad1vv1 those are good ideas.  I am not sure if I far I will get on the special book,  however, I really like adding titles to the processors so that they would be easier to identify.

**Comment by vlad1vv1** [comment]
ОК, many thanks.
