### ISSUE TITLE
Only allow arithmetic instructions to use the general purpose registers

### ISSUE THREAD

**Issue by frodare** [ToroCraft/Minecoprocessors#32]

**Comment by frodare** [comment]
This would be more realistic, but maybe just add annoyance for people learning assembly?

For instance, this example circuit would need to additional lines.

```Assembly
mov ports, 0010b
start:
cmp pb, 0 ;FAIL
jz start
mov pf, 1
mov pf, 0
mov pf, 1
mov pf, 0
wait:
cmp pb, 1 ;FAIL
jz wait
jmp start
```

**Comment by josephcsible** [comment]
I'm personally not a fan of this idea, due to it making programs more complicated as you mentioned, plus because CISC architectures are a thing, so this doesn't really make it more realistic.

**Comment by frodare** [comment]
Thanks for the input, I was torn on this one.  That reminds me I totally forgot about memory addressing, which would be a better use of time.
