### ISSUE TITLE
Transfer the entire byte from one port to another when two processors are connected

### ISSUE THREAD

**Issue by frodare** [ToroCraft/Minecoprocessors#40]

**Comment by josephcsible** [comment]
How will you be able to "connect" processors? Will they have to be adjacent, or are you going to add some sort of cable?

**Comment by frodare** [comment]
In this case they would need to be adjacent.  

I originally was planning to make a different mod that added redstone buses.  The buses would transfer an 8 bit signal and have pin blocks that you could connect to them to access the individual signals.  Bus repeaters would be needed too.  It sounded like a fun idea, but I ran out of steam.  It also bothered me that the buses would need to be tile entities, but maybe that wouldn't really be an issue.
