### ISSUE TITLE
Signs as screens

### ISSUE THREAD

**Issue by frodare** [ToroCraft/Minecoprocessors#41]
processor-opaque_block-sign

Have signs update their content to print out the data in ASCII from the processors memory when they are connected to an opaque block that is connected to a processor port.

The memory address to start from could be determined by the value in that port.

**Comment by josephcsible** [comment]
Instead of hijacking signs, could a dedicated block be added for the purpose? Then it could enable both input and output to the processor.

**Comment by frodare** [comment]
That is certainly an option, however, when possible I really try to use as much of the vanilla block, items,  textures and style as possible.  I would want to try to implement it with vanilla signs first and see how it goes.  

Interesting idea about an input!  We could probably use vanilla signs for that too, but yeah ... that would be an unpleasant process.  Actually, re-writable signs would be a good standalone mod if no one has done that already.
