### ISSUE TITLE
Why save compiled program to NBT?

### ISSUE THREAD

**Issue by josephcsible** [ToroCraft/Minecoprocessors#48]
https://github.com/ToroCraft/Minecoprocessors/blob/aa3f07e9bdd9d7ddfe9f4f2e71bade279d4c1131/src/main/java/net/torocraft/minecoprocessors/processor/Processor.java#L169-L183

Is there a reason that we need to save `program` and `labels` to NBT? Instead of doing this, could we just re-parse the book whenever we load the rest of our data from NBT?

**Comment by frodare** [comment]
Removing that would be a good optimization. It seems like it would work without it, certainly worth a shot.  Before we removing this code, let me fix the stack NBT serialization.
