### ISSUE TITLE
new version v3 crash on server

### ISSUE THREAD

**Issue by Zafaranec** [ToroCraft/Minecoprocessors#51]
Hi, new version 1.12.1-3 crash on my server but previous version not, here is my crashlog: [https://pastebin.com/xAUbLaj6](url)

**Comment by frodare** [comment]
Thanks for letting me know! I will get that fixed tonight.

**Comment by Zafaranec** [comment]
Thanks for react and fix :)

**Comment by frodare** [comment]
Notes:

https://github.com/ToroCraft/Minecoprocessors/blob/994769da2811675ef2c254e81ec8484c76259daf/src/main/java/net/torocraft/minecoprocessors/items/ItemBookCode.java#L131-L136

add `@SideOnly(Side.CLIENT)`

**Comment by frodare** [comment]
@Zafaranec this should be fixed in [1.12.1-4](https://minecraft.curseforge.com/projects/minecoprocessors/files/2485226), thanks again for bringing this to my attention!

**Comment by Zafaranec** [comment]
no problem, thank for awesome mod.
