### ISSUE TITLE
Overclocked processors have a broken model before being placed ingame

### ISSUE THREAD

**Issue by Sunconure11** [ToroCraft/Minecoprocessors#52]

**Comment by frodare** [comment]
@Sunconure11, thanks for letting me know about this and sorry for the delay in responding!  I am having trouble reproducing this issue.   Do I need to do something other than simply hold the overclocked processor so see the glitch?

**Comment by Sunconure11** [comment]
You might want to try later versions of Forge, as rendering changed a tad bit.

**Comment by frodare** [comment]
I just updated to 14.23.4.2746 and I am still not see the issue, maybe it was something that was fixed in forge?

![2018-08-07_07 52 18](https://user-images.githubusercontent.com/795621/43774436-146c01d8-9a17-11e8-8f83-7690d12d3eef.png)

**Comment by frodare** [comment]
... or maybe me simply updating to the latest version will fix the issue.  I hopefully will be uploading a new version soon that will be built against 14.23.4.2746.

**Comment by frodare** [comment]
I have updated the mod to the latest forge as 1.12.2-5, hopefully that fixes this issue.  If not please let me know and take a screen shot if possible.
