### ISSUE TITLE
1.14 porting branch ;)

### ISSUE THREAD

**Issue by stfwi** [ToroCraft/Minecoprocessors#56]
Hi Toro, I prepared a pull request for porting the mod to 1.14, could you take a peek and, if acceptable, make a 1.14 branch here in the main repo, where I could file the PR?

The forked porting branch is here: https://github.com/stfwi/Minecoprocessors/tree/mc1.14-porting.

It's far from done, but the basics are already ported.

**Comment by frodare** [comment]
Awesome! I created 1.14.4 branch, fire away.
