### ISSUE TITLE
1.15.2 branch ;-)

### ISSUE THREAD

**Issue by stfwi** [ToroCraft/Minecoprocessors#62]
Hi frodare, could you add a 1.15.2 branch derived from the 1.14.4 HEAD? Got a port ready ;-)

![2020-03-25_12 54 19](https://user-images.githubusercontent.com/28822525/77534371-ceb0d080-6e98-11ea-9581-92c4022e151e.png)

Cheers, wile -

**Comment by frodare** [comment]
Awesome, done.
